import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const downloadReport = (data) => {
  const doc = new jsPDF();

  // ==========================
  // HEADER
  // ==========================
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("TaskSphere", 14, 15);

  doc.setFontSize(11);
  doc.text("Dashboard Analytics Report", 14, 23);

  // ==========================
  // USER DETAILS
  // ==========================
  doc.setTextColor(40);

  autoTable(doc,{
    startY:40,

    theme:"grid",

    head:[
        ["Report Information",""]
    ],

    body:[
        ["Generated By",data.generatedBy],
        ["Role",data.role],
        ["Generated On",new Date().toLocaleString()]
    ]
    
});


  // ==========================
// DASHBOARD SUMMARY TABLE
// ==========================

let currentY = doc.lastAutoTable.finalY + 12;

autoTable(doc, {
  startY: currentY,

  head: [["Dashboard Metric", "Value"]],

  body: [
    ["Total Tasks", data.totalTasks],
    ["Approved Tasks", data.approvedTasks],
    ["Pending Approval", data.pendingApprovals],
    ["Tasks In Progress", data.inProgressTasks],
    ["To Do Tasks", data.todoTasks],
    ["Rejected Tasks", data.rejectedTasks],
    ["Overdue Tasks", data.overdueTasks],
    ["Active Members", data.activeMembers],
    ["Total Members", data.totalMembers],
  ],

  headStyles: {
    fillColor: [37, 99, 235],
    textColor: 255,
    halign: "center",
  },

  alternateRowStyles: {
    fillColor: [245, 247, 250],
  },

  styles: {
    fontSize: 10,
  },
});

currentY = doc.lastAutoTable.finalY + 12;

  // ==========================
// EXECUTIVE SUMMARY
// ==========================

autoTable(doc, {
  startY: currentY,

  head: [["Executive Summary"]],

  body: [[
`This report summarizes the current TaskSphere dashboard.

Total Tasks : ${data.totalTasks}

Approved Tasks : ${data.approvedTasks}

Pending Approval : ${data.pendingApprovals}

Tasks In Progress : ${data.inProgressTasks}

Overdue Tasks : ${data.overdueTasks}

The report highlights the team's productivity
and the current status of task execution.`
  ]],

  theme: "grid",

  styles: {
    fontSize: 11,
    cellPadding: 5,
    overflow: "linebreak",
    valign: "middle"
  },

  headStyles: {
    fillColor: [37, 99, 235],
    textColor: 255
  }
});

currentY = doc.lastAutoTable.finalY + 12;

 // ==========================
// PERFORMANCE ANALYSIS
// ==========================

const completionRate =
  data.totalTasks === 0
    ? 0
    : Math.round((data.approvedTasks / data.totalTasks) * 100);

autoTable(doc, {
  startY: currentY,

  head: [["Performance Analysis"]],

  body: [[
`Current Completion Rate : ${completionRate} %

Overall workflow is healthy.

Pending approvals should be monitored.

Overdue tasks should be reviewed.

Rejected tasks require attention.

Regular monitoring of tasks will improve
overall productivity and workflow efficiency.`
  ]],

  theme: "grid",

  styles: {
    fontSize: 11,
    cellPadding: 5,
    overflow: "linebreak"
  },

  headStyles: {
    fillColor: [37, 99, 235],
    textColor: 255
  }
});

currentY = doc.lastAutoTable.finalY + 12;

  // ==========================
// RECOMMENDATIONS
// ==========================

autoTable(doc, {
  startY: currentY,

  head: [["Recommendations"]],

  body: [
    ["Review overdue tasks."],
    ["Approve completed tasks."],
    ["Monitor team workload."],
    ["Increase completion rate."],
    ["Track pending approvals."]
  ],

  theme: "grid",

  styles: {
    fontSize: 11,
    cellPadding: 5
  },

  headStyles: {
    fillColor: [37, 99, 235],
    textColor: 255
  }
});

currentY = doc.lastAutoTable.finalY + 12;


// ======================================
// FOOTER (ADD THIS HERE)
// ======================================

const pageCount = doc.getNumberOfPages();

for (let i = 1; i <= pageCount; i++) {

  doc.setPage(i);

  const pageHeight = doc.internal.pageSize.height;

  doc.setDrawColor(180);
  doc.line(15, pageHeight - 12, 195, pageHeight - 12);

  doc.setFontSize(9);
  doc.setTextColor(100);

  doc.text(
    "Generated by TaskSphere",
    15,
    pageHeight - 5
  );

  doc.text(
    `Page ${i} of ${pageCount}`,
    170,
    pageHeight - 5
  );
}

// ======================================
// SAVE PDF (LAST LINE)
// ======================================

doc.save(`TaskSphere_Report_${Date.now()}.pdf`);
};